<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 64" tests="1" total_time="Finished in: 0.00 secs."/>
    <test location="/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/nmea_parser_test.py" status="error" test="NmeaParserTest.test_rmc_1" time="">
        <stdout/>
        <stderr>
            <![CDATA[Traceback (most recent call last):
  File "/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/nmea_parser_test.py", line 19, in test_rmc_1
    test_extractor.extractData(test_fields, NmeaParserTest.test_state)
  File "/Users/jeff/Documents/workspaces/dme/track_logger_converter/parsers/nmea_parser.py", line 32, in extractData
    gps_kph = field_data[NmeaRmcExtractor.Fields.Speed] * 1.852
TypeError: can't multiply sequence by non-int of type 'float'
]]>
        </stderr>
    </test>
    <launch mode="run">
        <launch_memento>
            <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="track_logger_converter nmea_parser_test.py"/>
]]>
        </launch_memento>
    </launch>
</pydev-testsuite>
